module Zavudev
  module Models
    type broadcast_list_params =
      {
        cursor: String,
        limit: Integer,
        status: Zavudev::Models::broadcast_status
      }
      & Zavudev::Internal::Type::request_parameters

    class BroadcastListParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader status: Zavudev::Models::broadcast_status?

      def status=: (
        Zavudev::Models::broadcast_status
      ) -> Zavudev::Models::broadcast_status

      def initialize: (
        ?cursor: String,
        ?limit: Integer,
        ?status: Zavudev::Models::broadcast_status,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String,
        limit: Integer,
        status: Zavudev::Models::broadcast_status,
        request_options: Zavudev::RequestOptions
      }
    end
  end
end
