module Zavudev
  module Models
    type broadcast_cancel_response = { broadcast: Zavudev::Broadcast }

    class BroadcastCancelResponse < Zavudev::Internal::Type::BaseModel
      attr_accessor broadcast: Zavudev::Broadcast

      def initialize: (broadcast: Zavudev::Broadcast) -> void

      def to_hash: -> { broadcast: Zavudev::Broadcast }
    end
  end
end
