module Zavudev
  module Models
    type contact =
      {
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        channels: ::Array[Zavudev::Contact::Channel],
        country_code: String,
        default_channel: Zavudev::Models::Contact::default_channel,
        display_name: String,
        phone_number: String,
        primary_email: String,
        primary_phone: String,
        profile_name: String?,
        suggested_merge_with: String,
        updated_at: Time
      }

    class Contact < Zavudev::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor available_channels: ::Array[String]

      attr_accessor created_at: Time

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor verified: bool

      attr_reader channels: ::Array[Zavudev::Contact::Channel]?

      def channels=: (
        ::Array[Zavudev::Contact::Channel]
      ) -> ::Array[Zavudev::Contact::Channel]

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader default_channel: Zavudev::Models::Contact::default_channel?

      def default_channel=: (
        Zavudev::Models::Contact::default_channel
      ) -> Zavudev::Models::Contact::default_channel

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader primary_email: String?

      def primary_email=: (String) -> String

      attr_reader primary_phone: String?

      def primary_phone=: (String) -> String

      attr_accessor profile_name: String?

      attr_reader suggested_merge_with: String?

      def suggested_merge_with=: (String) -> String

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      def initialize: (
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        ?channels: ::Array[Zavudev::Contact::Channel],
        ?country_code: String,
        ?default_channel: Zavudev::Models::Contact::default_channel,
        ?display_name: String,
        ?phone_number: String,
        ?primary_email: String,
        ?primary_phone: String,
        ?profile_name: String?,
        ?suggested_merge_with: String,
        ?updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        channels: ::Array[Zavudev::Contact::Channel],
        country_code: String,
        default_channel: Zavudev::Models::Contact::default_channel,
        display_name: String,
        phone_number: String,
        primary_email: String,
        primary_phone: String,
        profile_name: String?,
        suggested_merge_with: String,
        updated_at: Time
      }

      type channel =
        {
          id: String,
          channel: Zavudev::Models::Contact::Channel::channel,
          created_at: Time,
          identifier: String,
          is_primary: bool,
          verified: bool,
          country_code: String,
          label: String,
          last_inbound_at: Time,
          metadata: ::Hash[Symbol, String],
          metrics: Zavudev::Contact::Channel::Metrics,
          updated_at: Time
        }

      class Channel < Zavudev::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor channel: Zavudev::Models::Contact::Channel::channel

        attr_accessor created_at: Time

        attr_accessor identifier: String

        attr_accessor is_primary: bool

        attr_accessor verified: bool

        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader label: String?

        def label=: (String) -> String

        attr_reader last_inbound_at: Time?

        def last_inbound_at=: (Time) -> Time

        attr_reader metadata: ::Hash[Symbol, String]?

        def metadata=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader metrics: Zavudev::Contact::Channel::Metrics?

        def metrics=: (
          Zavudev::Contact::Channel::Metrics
        ) -> Zavudev::Contact::Channel::Metrics

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        def initialize: (
          id: String,
          channel: Zavudev::Models::Contact::Channel::channel,
          created_at: Time,
          identifier: String,
          is_primary: bool,
          verified: bool,
          ?country_code: String,
          ?label: String,
          ?last_inbound_at: Time,
          ?metadata: ::Hash[Symbol, String],
          ?metrics: Zavudev::Contact::Channel::Metrics,
          ?updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          channel: Zavudev::Models::Contact::Channel::channel,
          created_at: Time,
          identifier: String,
          is_primary: bool,
          verified: bool,
          country_code: String,
          label: String,
          last_inbound_at: Time,
          metadata: ::Hash[Symbol, String],
          metrics: Zavudev::Contact::Channel::Metrics,
          updated_at: Time
        }

        type channel = :sms | :whatsapp | :email | :telegram | :voice

        module Channel
          extend Zavudev::Internal::Type::Enum

          SMS: :sms
          WHATSAPP: :whatsapp
          EMAIL: :email
          TELEGRAM: :telegram
          VOICE: :voice

          def self?.values: -> ::Array[Zavudev::Models::Contact::Channel::channel]
        end

        type metrics =
          {
            avg_delivery_time_ms: Float,
            failure_count: Integer,
            last_success_at: Time,
            success_count: Integer,
            total_attempts: Integer
          }

        class Metrics < Zavudev::Internal::Type::BaseModel
          attr_reader avg_delivery_time_ms: Float?

          def avg_delivery_time_ms=: (Float) -> Float

          attr_reader failure_count: Integer?

          def failure_count=: (Integer) -> Integer

          attr_reader last_success_at: Time?

          def last_success_at=: (Time) -> Time

          attr_reader success_count: Integer?

          def success_count=: (Integer) -> Integer

          attr_reader total_attempts: Integer?

          def total_attempts=: (Integer) -> Integer

          def initialize: (
            ?avg_delivery_time_ms: Float,
            ?failure_count: Integer,
            ?last_success_at: Time,
            ?success_count: Integer,
            ?total_attempts: Integer
          ) -> void

          def to_hash: -> {
            avg_delivery_time_ms: Float,
            failure_count: Integer,
            last_success_at: Time,
            success_count: Integer,
            total_attempts: Integer
          }
        end
      end

      type default_channel =
        :sms | :whatsapp | :telegram | :email | :instagram | :voice

      module DefaultChannel
        extend Zavudev::Internal::Type::Enum

        SMS: :sms
        WHATSAPP: :whatsapp
        TELEGRAM: :telegram
        EMAIL: :email
        INSTAGRAM: :instagram
        VOICE: :voice

        def self?.values: -> ::Array[Zavudev::Models::Contact::default_channel]
      end
    end
  end
end
