module Zavudev
  module Models
    type contact =
      {
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        channels: ::Array[Zavudev::ContactChannel],
        country_code: String,
        default_channel: Zavudev::Models::Contact::default_channel,
        display_name: String,
        phone_number: String,
        primary_email: String,
        primary_phone: String,
        profile_name: String?,
        suggested_merge_with: String,
        updated_at: Time
      }

    class Contact < Zavudev::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor available_channels: ::Array[String]

      attr_accessor created_at: Time

      attr_accessor metadata: ::Hash[Symbol, String]

      attr_accessor verified: bool

      attr_reader channels: ::Array[Zavudev::ContactChannel]?

      def channels=: (
        ::Array[Zavudev::ContactChannel]
      ) -> ::Array[Zavudev::ContactChannel]

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader default_channel: Zavudev::Models::Contact::default_channel?

      def default_channel=: (
        Zavudev::Models::Contact::default_channel
      ) -> Zavudev::Models::Contact::default_channel

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader primary_email: String?

      def primary_email=: (String) -> String

      attr_reader primary_phone: String?

      def primary_phone=: (String) -> String

      attr_accessor profile_name: String?

      attr_reader suggested_merge_with: String?

      def suggested_merge_with=: (String) -> String

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      def initialize: (
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        ?channels: ::Array[Zavudev::ContactChannel],
        ?country_code: String,
        ?default_channel: Zavudev::Models::Contact::default_channel,
        ?display_name: String,
        ?phone_number: String,
        ?primary_email: String,
        ?primary_phone: String,
        ?profile_name: String?,
        ?suggested_merge_with: String,
        ?updated_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        available_channels: ::Array[String],
        created_at: Time,
        metadata: ::Hash[Symbol, String],
        verified: bool,
        channels: ::Array[Zavudev::ContactChannel],
        country_code: String,
        default_channel: Zavudev::Models::Contact::default_channel,
        display_name: String,
        phone_number: String,
        primary_email: String,
        primary_phone: String,
        profile_name: String?,
        suggested_merge_with: String,
        updated_at: Time
      }

      type default_channel =
        :sms | :whatsapp | :telegram | :email | :instagram | :voice

      module DefaultChannel
        extend Zavudev::Internal::Type::Enum

        SMS: :sms
        WHATSAPP: :whatsapp
        TELEGRAM: :telegram
        EMAIL: :email
        INSTAGRAM: :instagram
        VOICE: :voice

        def self?.values: -> ::Array[Zavudev::Models::Contact::default_channel]
      end
    end
  end
end
