module Zavudev
  module Models
    type export_list_params =
      {
        cursor: String,
        limit: Integer,
        status: Zavudev::Models::ExportListParams::status
      }
      & Zavudev::Internal::Type::request_parameters

    class ExportListParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader status: Zavudev::Models::ExportListParams::status?

      def status=: (
        Zavudev::Models::ExportListParams::status
      ) -> Zavudev::Models::ExportListParams::status

      def initialize: (
        ?cursor: String,
        ?limit: Integer,
        ?status: Zavudev::Models::ExportListParams::status,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> {
        cursor: String,
        limit: Integer,
        status: Zavudev::Models::ExportListParams::status,
        request_options: Zavudev::RequestOptions
      }

      type status = :pending | :processing | :completed | :failed

      module Status
        extend Zavudev::Internal::Type::Enum

        PENDING: :pending
        PROCESSING: :processing
        COMPLETED: :completed
        FAILED: :failed

        def self?.values: -> ::Array[Zavudev::Models::ExportListParams::status]
      end
    end
  end
end
