module Zavudev
  module Models
    type function_list_event_types_params =
      {  } & Zavudev::Internal::Type::request_parameters

    class FunctionListEventTypesParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      def initialize: (?request_options: Zavudev::request_opts) -> void

      def to_hash: -> { request_options: Zavudev::RequestOptions }
    end
  end
end
