module Zavudev
  module Models
    type invitation_cancel_response = { invitation: Zavudev::Invitation }

    class InvitationCancelResponse < Zavudev::Internal::Type::BaseModel
      attr_accessor invitation: Zavudev::Invitation

      def initialize: (invitation: Zavudev::Invitation) -> void

      def to_hash: -> { invitation: Zavudev::Invitation }
    end
  end
end
