module Zavudev
  module Models
    type invitation_retrieve_response = { invitation: Zavudev::Invitation }

    class InvitationRetrieveResponse < Zavudev::Internal::Type::BaseModel
      attr_accessor invitation: Zavudev::Invitation

      def initialize: (invitation: Zavudev::Invitation) -> void

      def to_hash: -> { invitation: Zavudev::Invitation }
    end
  end
end
