module Zavudev
  module Models
    type phone_number_pricing =
      { is_free_eligible: bool, monthly_price: Float, upfront_price: Float }

    class PhoneNumberPricing < Zavudev::Internal::Type::BaseModel
      attr_reader is_free_eligible: bool?

      def is_free_eligible=: (bool) -> bool

      attr_reader monthly_price: Float?

      def monthly_price=: (Float) -> Float

      attr_reader upfront_price: Float?

      def upfront_price=: (Float) -> Float

      def initialize: (
        ?is_free_eligible: bool,
        ?monthly_price: Float,
        ?upfront_price: Float
      ) -> void

      def to_hash: -> {
        is_free_eligible: bool,
        monthly_price: Float,
        upfront_price: Float
      }
    end
  end
end
