module Zavudev
  module Models
    type phone_number_retrieve_response =
      { phone_number: Zavudev::OwnedPhoneNumber }

    class PhoneNumberRetrieveResponse < Zavudev::Internal::Type::BaseModel
      attr_accessor phone_number: Zavudev::OwnedPhoneNumber

      def initialize: (phone_number: Zavudev::OwnedPhoneNumber) -> void

      def to_hash: -> { phone_number: Zavudev::OwnedPhoneNumber }
    end
  end
end
