module Zavudev
  module Models
    type regulatory_document_retrieve_params =
      { document_id: String } & Zavudev::Internal::Type::request_parameters

    class RegulatoryDocumentRetrieveParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_accessor document_id: String

      def initialize: (
        document_id: String,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> {
        document_id: String,
        request_options: Zavudev::RequestOptions
      }
    end
  end
end
