module Zavudev
  module Models
    type sender_create_params =
      {
        name: String,
        email_address: String,
        email_domain_id: String,
        email_from_name: String,
        email_receiving_enabled: bool,
        enable_voice: bool,
        phone_number: String,
        set_as_default: bool,
        webhook_events: ::Array[Zavudev::Models::webhook_event],
        webhook_url: String
      }
      & Zavudev::Internal::Type::request_parameters

    class SenderCreateParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_reader email_address: String?

      def email_address=: (String) -> String

      attr_reader email_domain_id: String?

      def email_domain_id=: (String) -> String

      attr_reader email_from_name: String?

      def email_from_name=: (String) -> String

      attr_reader email_receiving_enabled: bool?

      def email_receiving_enabled=: (bool) -> bool

      attr_reader enable_voice: bool?

      def enable_voice=: (bool) -> bool

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader set_as_default: bool?

      def set_as_default=: (bool) -> bool

      attr_reader webhook_events: ::Array[Zavudev::Models::webhook_event]?

      def webhook_events=: (
        ::Array[Zavudev::Models::webhook_event]
      ) -> ::Array[Zavudev::Models::webhook_event]

      attr_reader webhook_url: String?

      def webhook_url=: (String) -> String

      def initialize: (
        name: String,
        ?email_address: String,
        ?email_domain_id: String,
        ?email_from_name: String,
        ?email_receiving_enabled: bool,
        ?enable_voice: bool,
        ?phone_number: String,
        ?set_as_default: bool,
        ?webhook_events: ::Array[Zavudev::Models::webhook_event],
        ?webhook_url: String,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        email_address: String,
        email_domain_id: String,
        email_from_name: String,
        email_receiving_enabled: bool,
        enable_voice: bool,
        phone_number: String,
        set_as_default: bool,
        webhook_events: ::Array[Zavudev::Models::webhook_event],
        webhook_url: String,
        request_options: Zavudev::RequestOptions
      }
    end
  end
end
