module Zavudev
  module Models
    type sub_account_retrieve_params =
      { id: String } & Zavudev::Internal::Type::request_parameters

    class SubAccountRetrieveParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: Zavudev::RequestOptions }
    end
  end
end
