module Zavudev
  module Models
    type template_sync_params =
      { sender_id: String } & Zavudev::Internal::Type::request_parameters

    class TemplateSyncParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_reader sender_id: String?

      def sender_id=: (String) -> String

      def initialize: (
        ?sender_id: String,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> {
        sender_id: String,
        request_options: Zavudev::RequestOptions
      }
    end
  end
end
