module Zavudev
  module Models
    type url_submit_for_verification_params =
      { url: String } & Zavudev::Internal::Type::request_parameters

    class URLSubmitForVerificationParams < Zavudev::Internal::Type::BaseModel
      extend Zavudev::Internal::Type::RequestParameters::Converter
      include Zavudev::Internal::Type::RequestParameters

      attr_accessor url: String

      def initialize: (
        url: String,
        ?request_options: Zavudev::request_opts
      ) -> void

      def to_hash: -> { url: String, request_options: Zavudev::RequestOptions }
    end
  end
end
