module Zavudev
  module Models
    type webhook_secret_response = { secret: String }

    class WebhookSecretResponse < Zavudev::Internal::Type::BaseModel
      attr_accessor secret: String

      def initialize: (secret: String) -> void

      def to_hash: -> { secret: String }
    end
  end
end
