module Zavudev
  module Models
    type webhook_event =
      :"message.queued"
      | :"message.sent"
      | :"message.delivered"
      | :"message.read"
      | :"message.status"
      | :"message.failed"
      | :"message.inbound"
      | :"message.unsupported"
      | :"broadcast.status_changed"
      | :"conversation.new"
      | :"template.status_changed"
      | :"invitation.status_changed"
      | :"call.initiated"
      | :"call.answered"
      | :"call.completed"
      | :"call.failed"
      | :"domain.verified"
      | :"domain.failed"

    module WebhookEvent
      extend Zavudev::Internal::Type::Enum

      MESSAGE_QUEUED: :"message.queued"
      MESSAGE_SENT: :"message.sent"
      MESSAGE_DELIVERED: :"message.delivered"
      MESSAGE_READ: :"message.read"
      MESSAGE_STATUS: :"message.status"
      MESSAGE_FAILED: :"message.failed"
      MESSAGE_INBOUND: :"message.inbound"
      MESSAGE_UNSUPPORTED: :"message.unsupported"
      BROADCAST_STATUS_CHANGED: :"broadcast.status_changed"
      CONVERSATION_NEW: :"conversation.new"
      TEMPLATE_STATUS_CHANGED: :"template.status_changed"
      INVITATION_STATUS_CHANGED: :"invitation.status_changed"
      CALL_INITIATED: :"call.initiated"
      CALL_ANSWERED: :"call.answered"
      CALL_COMPLETED: :"call.completed"
      CALL_FAILED: :"call.failed"
      DOMAIN_VERIFIED: :"domain.verified"
      DOMAIN_FAILED: :"domain.failed"

      def self?.values: -> ::Array[Zavudev::Models::webhook_event]
    end
  end
end
