module Zavudev
  module Models
    type whatsapp_business_profile =
      {
        about: String,
        address: String,
        description: String,
        email: String,
        profile_picture_url: String,
        vertical: Zavudev::Models::whatsapp_business_profile_vertical,
        websites: ::Array[String]
      }

    class WhatsappBusinessProfile < Zavudev::Internal::Type::BaseModel
      attr_reader about: String?

      def about=: (String) -> String

      attr_reader address: String?

      def address=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader profile_picture_url: String?

      def profile_picture_url=: (String) -> String

      attr_reader vertical: Zavudev::Models::whatsapp_business_profile_vertical?

      def vertical=: (
        Zavudev::Models::whatsapp_business_profile_vertical
      ) -> Zavudev::Models::whatsapp_business_profile_vertical

      attr_reader websites: ::Array[String]?

      def websites=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?about: String,
        ?address: String,
        ?description: String,
        ?email: String,
        ?profile_picture_url: String,
        ?vertical: Zavudev::Models::whatsapp_business_profile_vertical,
        ?websites: ::Array[String]
      ) -> void

      def to_hash: -> {
        about: String,
        address: String,
        description: String,
        email: String,
        profile_picture_url: String,
        vertical: Zavudev::Models::whatsapp_business_profile_vertical,
        websites: ::Array[String]
      }
    end
  end
end
