module Zavudev
  module Internal
    class Cursor[Elem]
      include Zavudev::Internal::Type::BasePage[Elem]

      attr_accessor items: ::Array[Elem]?

      attr_accessor next_cursor: String

      def inspect: -> String
    end
  end
end
