module Zavudev
  module Models
    module Senders
      class AgentTool = Agent::AgentTool

      module Agent
        type agent_tool =
          {
            id: String,
            agent_id: String,
            created_at: Time,
            description: String,
            enabled: bool,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolParameters,
            updated_at: Time,
            webhook_url: String
          }

        class AgentTool < Zavudev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor agent_id: String

          attr_accessor created_at: Time

          attr_accessor description: String

          attr_accessor enabled: bool

          attr_accessor name: String

          attr_accessor parameters: Zavudev::Senders::Agent::ToolParameters

          attr_accessor updated_at: Time

          attr_accessor webhook_url: String

          def initialize: (
            id: String,
            agent_id: String,
            created_at: Time,
            description: String,
            enabled: bool,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolParameters,
            updated_at: Time,
            webhook_url: String
          ) -> void

          def to_hash: -> {
            id: String,
            agent_id: String,
            created_at: Time,
            description: String,
            enabled: bool,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolParameters,
            updated_at: Time,
            webhook_url: String
          }
        end
      end
    end
  end
end
