module Zavudev
  module Models
    module Senders
      class AgentFlow = Agent::AgentFlow

      module Agent
        type agent_flow =
          {
            id: String,
            agent_id: String,
            created_at: Time,
            enabled: bool,
            name: String,
            priority: Integer,
            steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            trigger: Zavudev::Senders::Agent::FlowTrigger,
            updated_at: Time,
            description: String?
          }

        class AgentFlow < Zavudev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor agent_id: String

          attr_accessor created_at: Time

          attr_accessor enabled: bool

          attr_accessor name: String

          attr_accessor priority: Integer

          attr_accessor steps: ::Array[Zavudev::Senders::Agent::FlowStep]

          attr_accessor trigger: Zavudev::Senders::Agent::FlowTrigger

          attr_accessor updated_at: Time

          attr_accessor description: String?

          def initialize: (
            id: String,
            agent_id: String,
            created_at: Time,
            enabled: bool,
            name: String,
            priority: Integer,
            steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            trigger: Zavudev::Senders::Agent::FlowTrigger,
            updated_at: Time,
            ?description: String?
          ) -> void

          def to_hash: -> {
            id: String,
            agent_id: String,
            created_at: Time,
            enabled: bool,
            name: String,
            priority: Integer,
            steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            trigger: Zavudev::Senders::Agent::FlowTrigger,
            updated_at: Time,
            description: String?
          }
        end
      end
    end
  end
end
