module Zavudev
  module Models
    module Senders
      module Agent
        type flow_update_params =
          {
            sender_id: String,
            flow_id: String,
            description: String,
            enabled: bool,
            name: String,
            priority: Integer,
            steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            trigger: Zavudev::Senders::Agent::FlowTrigger
          }
          & Zavudev::Internal::Type::request_parameters

        class FlowUpdateParams < Zavudev::Internal::Type::BaseModel
          extend Zavudev::Internal::Type::RequestParameters::Converter
          include Zavudev::Internal::Type::RequestParameters

          attr_accessor sender_id: String

          attr_accessor flow_id: String

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader enabled: bool?

          def enabled=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader priority: Integer?

          def priority=: (Integer) -> Integer

          attr_reader steps: ::Array[Zavudev::Senders::Agent::FlowStep]?

          def steps=: (
            ::Array[Zavudev::Senders::Agent::FlowStep]
          ) -> ::Array[Zavudev::Senders::Agent::FlowStep]

          attr_reader trigger: Zavudev::Senders::Agent::FlowTrigger?

          def trigger=: (
            Zavudev::Senders::Agent::FlowTrigger
          ) -> Zavudev::Senders::Agent::FlowTrigger

          def initialize: (
            sender_id: String,
            flow_id: String,
            ?description: String,
            ?enabled: bool,
            ?name: String,
            ?priority: Integer,
            ?steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            ?trigger: Zavudev::Senders::Agent::FlowTrigger,
            ?request_options: Zavudev::request_opts
          ) -> void

          def to_hash: -> {
            sender_id: String,
            flow_id: String,
            description: String,
            enabled: bool,
            name: String,
            priority: Integer,
            steps: ::Array[Zavudev::Senders::Agent::FlowStep],
            trigger: Zavudev::Senders::Agent::FlowTrigger,
            request_options: Zavudev::RequestOptions
          }
        end
      end
    end
  end
end
