module Zavudev
  module Models
    module Senders
      module Agent
        type knowledge_base_create_params =
          { sender_id: String, name: String, description: String }
          & Zavudev::Internal::Type::request_parameters

        class KnowledgeBaseCreateParams < Zavudev::Internal::Type::BaseModel
          extend Zavudev::Internal::Type::RequestParameters::Converter
          include Zavudev::Internal::Type::RequestParameters

          attr_accessor sender_id: String

          attr_accessor name: String

          attr_reader description: String?

          def description=: (String) -> String

          def initialize: (
            sender_id: String,
            name: String,
            ?description: String,
            ?request_options: Zavudev::request_opts
          ) -> void

          def to_hash: -> {
            sender_id: String,
            name: String,
            description: String,
            request_options: Zavudev::RequestOptions
          }
        end
      end
    end
  end
end
