module Zavudev
  module Models
    module Senders
      module Agent
        type knowledge_base_create_response =
          { knowledge_base: Zavudev::Senders::Agent::AgentKnowledgeBase }

        class KnowledgeBaseCreateResponse < Zavudev::Internal::Type::BaseModel
          attr_accessor knowledge_base: Zavudev::Senders::Agent::AgentKnowledgeBase

          def initialize: (
            knowledge_base: Zavudev::Senders::Agent::AgentKnowledgeBase
          ) -> void

          def to_hash: -> {
            knowledge_base: Zavudev::Senders::Agent::AgentKnowledgeBase
          }
        end
      end
    end
  end
end
