module Zavudev
  module Models
    module Senders
      module Agent
        type tool_create_params =
          {
            sender_id: String,
            description: String,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolCreateParams::Parameters,
            webhook_url: String,
            enabled: bool,
            webhook_secret: String
          }
          & Zavudev::Internal::Type::request_parameters

        class ToolCreateParams < Zavudev::Internal::Type::BaseModel
          extend Zavudev::Internal::Type::RequestParameters::Converter
          include Zavudev::Internal::Type::RequestParameters

          attr_accessor sender_id: String

          attr_accessor description: String

          attr_accessor name: String

          attr_accessor parameters: Zavudev::Senders::Agent::ToolCreateParams::Parameters

          attr_accessor webhook_url: String

          attr_reader enabled: bool?

          def enabled=: (bool) -> bool

          attr_reader webhook_secret: String?

          def webhook_secret=: (String) -> String

          def initialize: (
            sender_id: String,
            description: String,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolCreateParams::Parameters,
            webhook_url: String,
            ?enabled: bool,
            ?webhook_secret: String,
            ?request_options: Zavudev::request_opts
          ) -> void

          def to_hash: -> {
            sender_id: String,
            description: String,
            name: String,
            parameters: Zavudev::Senders::Agent::ToolCreateParams::Parameters,
            webhook_url: String,
            enabled: bool,
            webhook_secret: String,
            request_options: Zavudev::RequestOptions
          }

          type parameters =
            {
              properties: ::Hash[Symbol, Zavudev::Senders::Agent::ToolCreateParams::Parameters::Property],
              required: ::Array[String],
              type: Zavudev::Models::Senders::Agent::ToolCreateParams::Parameters::type_
            }

          class Parameters < Zavudev::Internal::Type::BaseModel
            attr_accessor properties: ::Hash[Symbol, Zavudev::Senders::Agent::ToolCreateParams::Parameters::Property]

            attr_accessor required: ::Array[String]

            attr_accessor type: Zavudev::Models::Senders::Agent::ToolCreateParams::Parameters::type_

            def initialize: (
              properties: ::Hash[Symbol, Zavudev::Senders::Agent::ToolCreateParams::Parameters::Property],
              required: ::Array[String],
              type: Zavudev::Models::Senders::Agent::ToolCreateParams::Parameters::type_
            ) -> void

            def to_hash: -> {
              properties: ::Hash[Symbol, Zavudev::Senders::Agent::ToolCreateParams::Parameters::Property],
              required: ::Array[String],
              type: Zavudev::Models::Senders::Agent::ToolCreateParams::Parameters::type_
            }

            type property = { description: String, type: String }

            class Property < Zavudev::Internal::Type::BaseModel
              attr_reader description: String?

              def description=: (String) -> String

              attr_reader type: String?

              def type=: (String) -> String

              def initialize: (?description: String, ?type: String) -> void

              def to_hash: -> { description: String, type: String }
            end

            type type_ = :object

            module Type
              extend Zavudev::Internal::Type::Enum

              OBJECT: :object

              def self?.values: -> ::Array[Zavudev::Models::Senders::Agent::ToolCreateParams::Parameters::type_]
            end
          end
        end
      end
    end
  end
end
