module Zavudev
  module Models
    module Functions
      type secret_list_response =
        {
          secrets: ::Array[Zavudev::Models::Functions::SecretListResponse::Secret]
        }

      class SecretListResponse < Zavudev::Internal::Type::BaseModel
        attr_accessor secrets: ::Array[Zavudev::Models::Functions::SecretListResponse::Secret]

        def initialize: (
          secrets: ::Array[Zavudev::Models::Functions::SecretListResponse::Secret]
        ) -> void

        def to_hash: -> {
          secrets: ::Array[Zavudev::Models::Functions::SecretListResponse::Secret]
        }

        type secret =
          {
            id: String,
            key: String,
            :value_last4 => String,
            created_at: Float,
            synced_to_aws: bool,
            updated_at: Float
          }

        class Secret < Zavudev::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor key: String

          attr_accessor value_last4: String

          attr_reader created_at: Float?

          def created_at=: (Float) -> Float

          attr_reader synced_to_aws: bool?

          def synced_to_aws=: (bool) -> bool

          attr_reader updated_at: Float?

          def updated_at=: (Float) -> Float

          def initialize: (
            id: String,
            key: String,
            value_last4: String,
            ?created_at: Float,
            ?synced_to_aws: bool,
            ?updated_at: Float
          ) -> void

          def to_hash: -> {
            id: String,
            key: String,
            :value_last4 => String,
            created_at: Float,
            synced_to_aws: bool,
            updated_at: Float
          }
        end
      end
    end
  end
end
