module Zavudev
  module Models
    module Contacts
      type channel_update_response = { channel: Zavudev::ContactChannel }

      class ChannelUpdateResponse < Zavudev::Internal::Type::BaseModel
        attr_accessor channel: Zavudev::ContactChannel

        def initialize: (channel: Zavudev::ContactChannel) -> void

        def to_hash: -> { channel: Zavudev::ContactChannel }
      end
    end
  end
end
