module Zavudev
  module Models
    module Senders
      type agent_create_params =
        {
          sender_id: String,
          model: String,
          name: String,
          provider: Zavudev::Models::Senders::agent_provider,
          system_prompt: String,
          api_key: String,
          context_window_messages: Integer,
          include_contact_metadata: bool,
          max_tokens: Integer,
          temperature: Float,
          trigger_on_channels: ::Array[String],
          trigger_on_message_types: ::Array[String],
          voice: Zavudev::Senders::AgentCreateParams::Voice
        }
        & Zavudev::Internal::Type::request_parameters

      class AgentCreateParams < Zavudev::Internal::Type::BaseModel
        extend Zavudev::Internal::Type::RequestParameters::Converter
        include Zavudev::Internal::Type::RequestParameters

        attr_accessor sender_id: String

        attr_accessor model: String

        attr_accessor name: String

        attr_accessor provider: Zavudev::Models::Senders::agent_provider

        attr_accessor system_prompt: String

        attr_reader api_key: String?

        def api_key=: (String) -> String

        attr_reader context_window_messages: Integer?

        def context_window_messages=: (Integer) -> Integer

        attr_reader include_contact_metadata: bool?

        def include_contact_metadata=: (bool) -> bool

        attr_reader max_tokens: Integer?

        def max_tokens=: (Integer) -> Integer

        attr_reader temperature: Float?

        def temperature=: (Float) -> Float

        attr_reader trigger_on_channels: ::Array[String]?

        def trigger_on_channels=: (::Array[String]) -> ::Array[String]

        attr_reader trigger_on_message_types: ::Array[String]?

        def trigger_on_message_types=: (::Array[String]) -> ::Array[String]

        attr_reader voice: Zavudev::Senders::AgentCreateParams::Voice?

        def voice=: (
          Zavudev::Senders::AgentCreateParams::Voice
        ) -> Zavudev::Senders::AgentCreateParams::Voice

        def initialize: (
          sender_id: String,
          model: String,
          name: String,
          provider: Zavudev::Models::Senders::agent_provider,
          system_prompt: String,
          ?api_key: String,
          ?context_window_messages: Integer,
          ?include_contact_metadata: bool,
          ?max_tokens: Integer,
          ?temperature: Float,
          ?trigger_on_channels: ::Array[String],
          ?trigger_on_message_types: ::Array[String],
          ?voice: Zavudev::Senders::AgentCreateParams::Voice,
          ?request_options: Zavudev::request_opts
        ) -> void

        def to_hash: -> {
          sender_id: String,
          model: String,
          name: String,
          provider: Zavudev::Models::Senders::agent_provider,
          system_prompt: String,
          api_key: String,
          context_window_messages: Integer,
          include_contact_metadata: bool,
          max_tokens: Integer,
          temperature: Float,
          trigger_on_channels: ::Array[String],
          trigger_on_message_types: ::Array[String],
          voice: Zavudev::Senders::AgentCreateParams::Voice,
          request_options: Zavudev::RequestOptions
        }

        type voice =
          {
            enabled: bool,
            greeting: String,
            greetings: ::Hash[Symbol, String],
            interruptible: bool,
            language: String,
            max_call_duration_minutes: Integer,
            max_idle_seconds: Integer,
            model: String,
            record_calls: bool,
            stt_model: String,
            stt_provider: String,
            transfer_phone_number: String,
            tts_provider: String,
            tts_voice_id: String,
            voicemail_action: Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action,
            voicemail_message: String,
            voice_speed: Float
          }

        class Voice < Zavudev::Internal::Type::BaseModel
          attr_accessor enabled: bool

          attr_reader greeting: String?

          def greeting=: (String) -> String

          attr_reader greetings: ::Hash[Symbol, String]?

          def greetings=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

          attr_reader interruptible: bool?

          def interruptible=: (bool) -> bool

          attr_reader language: String?

          def language=: (String) -> String

          attr_reader max_call_duration_minutes: Integer?

          def max_call_duration_minutes=: (Integer) -> Integer

          attr_reader max_idle_seconds: Integer?

          def max_idle_seconds=: (Integer) -> Integer

          attr_reader model: String?

          def model=: (String) -> String

          attr_reader record_calls: bool?

          def record_calls=: (bool) -> bool

          attr_reader stt_model: String?

          def stt_model=: (String) -> String

          attr_reader stt_provider: String?

          def stt_provider=: (String) -> String

          attr_reader transfer_phone_number: String?

          def transfer_phone_number=: (String) -> String

          attr_reader tts_provider: String?

          def tts_provider=: (String) -> String

          attr_reader tts_voice_id: String?

          def tts_voice_id=: (String) -> String

          attr_reader voicemail_action: Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action?

          def voicemail_action=: (
            Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action
          ) -> Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action

          attr_reader voicemail_message: String?

          def voicemail_message=: (String) -> String

          attr_reader voice_speed: Float?

          def voice_speed=: (Float) -> Float

          def initialize: (
            enabled: bool,
            ?greeting: String,
            ?greetings: ::Hash[Symbol, String],
            ?interruptible: bool,
            ?language: String,
            ?max_call_duration_minutes: Integer,
            ?max_idle_seconds: Integer,
            ?model: String,
            ?record_calls: bool,
            ?stt_model: String,
            ?stt_provider: String,
            ?transfer_phone_number: String,
            ?tts_provider: String,
            ?tts_voice_id: String,
            ?voicemail_action: Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action,
            ?voicemail_message: String,
            ?voice_speed: Float
          ) -> void

          def to_hash: -> {
            enabled: bool,
            greeting: String,
            greetings: ::Hash[Symbol, String],
            interruptible: bool,
            language: String,
            max_call_duration_minutes: Integer,
            max_idle_seconds: Integer,
            model: String,
            record_calls: bool,
            stt_model: String,
            stt_provider: String,
            transfer_phone_number: String,
            tts_provider: String,
            tts_voice_id: String,
            voicemail_action: Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action,
            voicemail_message: String,
            voice_speed: Float
          }

          type voicemail_action = :hangup | :leave_message

          module VoicemailAction
            extend Zavudev::Internal::Type::Enum

            HANGUP: :hangup
            LEAVE_MESSAGE: :leave_message

            def self?.values: -> ::Array[Zavudev::Models::Senders::AgentCreateParams::Voice::voicemail_action]
          end
        end
      end
    end
  end
end
