module Zavudev
  module Models
    module Number10dlc
      type campaign_submit_response =
        { campaign: Zavudev::Number10dlc::TenDlcCampaign }

      class CampaignSubmitResponse < Zavudev::Internal::Type::BaseModel
        attr_accessor campaign: Zavudev::Number10dlc::TenDlcCampaign

        def initialize: (campaign: Zavudev::Number10dlc::TenDlcCampaign) -> void

        def to_hash: -> { campaign: Zavudev::Number10dlc::TenDlcCampaign }
      end
    end
  end
end
