module Zavudev
  module Models
    module Senders
      module Agent
        module KnowledgeBases
          type document_retrieve_document_response =
            { document: Zavudev::Senders::Agent::AgentDocument }

          class DocumentRetrieveDocumentResponse < Zavudev::Internal::Type::BaseModel
            attr_accessor document: Zavudev::Senders::Agent::AgentDocument

            def initialize: (
              document: Zavudev::Senders::Agent::AgentDocument
            ) -> void

            def to_hash: -> { document: Zavudev::Senders::Agent::AgentDocument }
          end
        end
      end
    end
  end
end
