module Zavudev
  module Resources
    class Templates
      def create: (
        body: String,
        language: String,
        name: String,
        ?add_security_recommendation: bool,
        ?buttons: ::Array[Zavudev::TemplateCreateParams::Button],
        ?code_expiration_minutes: Integer,
        ?variables: ::Array[String],
        ?whatsapp_category: Zavudev::Models::whatsapp_category,
        ?request_options: Zavudev::request_opts
      ) -> Zavudev::Template

      def retrieve: (
        String template_id,
        ?request_options: Zavudev::request_opts
      ) -> Zavudev::Template

      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?request_options: Zavudev::request_opts
      ) -> Zavudev::Internal::Cursor[Zavudev::Template]

      def delete: (
        String template_id,
        ?request_options: Zavudev::request_opts
      ) -> nil

      def submit: (
        String template_id,
        sender_id: String,
        ?category: Zavudev::Models::whatsapp_category,
        ?request_options: Zavudev::request_opts
      ) -> Zavudev::Template

      def initialize: (client: Zavudev::Client) -> void
    end
  end
end
