module Zavudev
  class Client < Zavudev::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader messages: Zavudev::Resources::Messages

    attr_reader templates: Zavudev::Resources::Templates

    attr_reader senders: Zavudev::Resources::Senders

    attr_reader contacts: Zavudev::Resources::Contacts

    attr_reader broadcasts: Zavudev::Resources::Broadcasts

    attr_reader introspect: Zavudev::Resources::Introspect

    attr_reader phone_numbers: Zavudev::Resources::PhoneNumbers

    attr_reader addresses: Zavudev::Resources::Addresses

    attr_reader regulatory_documents: Zavudev::Resources::RegulatoryDocuments

    attr_reader invitations: Zavudev::Resources::Invitations

    attr_reader exports: Zavudev::Resources::Exports

    attr_reader urls: Zavudev::Resources::URLs

    attr_reader balance: Zavudev::Resources::Balance

    attr_reader plan: Zavudev::Resources::Plan

    attr_reader usage: Zavudev::Resources::Usage

    attr_reader sub_accounts: Zavudev::Resources::SubAccounts

    attr_reader number_10dlc: Zavudev::Resources::Number10dlc

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
